name: Setup Tests & Deployment
on:
  push:
    branches:
      - develop
  workflow_dispatch:
env:
  BIGSUN: ${{ secrets.BIGSUN }}
jobs:
  setup:
    name: Setup for Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
          cache: pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest --disable-warnings --cache-clear tests.py
  merge:
    name: Metge to main
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: ${{ secrets.BIGSUN }}
          